package info.elaina.bili.api.user.nav

data class Data(
    val isLogin: Boolean,
    val email_verified: Int,
    val face: String,
    val face_nft: Int,
    val face_nft_type: Int,
    val level_info: LevelInfo,
    val mid: Int,
    val mobile_verified: Int,
    val money: Double,
    val moral: Int,
    val official: Official,
    val officialVerify: OfficialVerify,
    val pendant: Pendant,
    val scores: Int,
    val uname: String,
    val vipDueDate: Long,
    val vipStatus: Int,
    val vipType: Int,
    val vip_pay_type: Int,
    val vip_theme_type: Int,
    val vip_label: VipLabel,
    val vip_avatar_subscript: Int,
    val vip_nickname_color: String,
    val vip: Vip,
    val wallet: Wallet,
    val has_shop: Boolean,
    val shop_url: String,
    val allowance_count: Int,
    val answer_status: Int,
    val is_senior_member: Int,
    val wbi_img: WbiImg,
    val is_jury: Boolean
)